# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /#about
    weight: 15
  - name: Publications
    url: /#papers
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Presentations
    url: /#talks
    weight: 40
  - name: Experience
    url: experience/
    weight: 50
  - name: CV
    url: uploads/resume.pdf
    weight: 60
